language: node_js

os:
  - linux

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - 'lts/*'

git:
  depth: 3

before_script:
  - yarn bootstrap

script:
  - yarn test
  - yarn build
